2023-05-20 10:47:31 ERROR: Exception on /url/create [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 380, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 186, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x10a354fd0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 398, in decorated_function
    if self.app.debug:
AttributeError: 'Cache' object has no attribute 'app'
2023-05-20 11:03:36 ERROR: Exception on /url/create [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 380, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 186, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x1075b3af0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 398, in decorated_function
    if self.app.debug:
AttributeError: 'Cache' object has no attribute 'app'
2023-05-20 11:05:08 ERROR: Exception on /url/create [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 380, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 186, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x1048b1ac0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 398, in decorated_function
    if self.app.debug:
AttributeError: 'Cache' object has no attribute 'app'
2023-05-20 11:15:02 ERROR: Exception on /url/create [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 380, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 186, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x1041fad90>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 398, in decorated_function
    if self.app.debug:
AttributeError: 'Cache' object has no attribute 'app'
2023-05-20 11:19:42 ERROR: Exception on /url/create [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 380, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 186, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x10369ab80>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 398, in decorated_function
    if self.app.debug:
AttributeError: 'Cache' object has no attribute 'app'
2023-05-20 11:19:59 ERROR: Exception on /url/create [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 380, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 186, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x10d15d0a0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 398, in decorated_function
    if self.app.debug:
AttributeError: 'Cache' object has no attribute 'app'
2023-05-20 11:24:54 INFO: CreateURL is called
2023-05-20 11:24:57 DEBUG: Created short url: <url ffd379a7-53cf-41b5-ba36-0029c918a2dd>
2023-05-20 11:33:25 INFO: CreateURL is called
2023-05-20 11:33:28 DEBUG: Created a short url: <url 4731fecd-2392-4ada-87e5-d83c64f6d8b2>
